feat: change package json for husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,8 +3,10 @@
 
 echo 'Testing your project...'
 
-pnpm run test-all || (
-  echo 'Failed tests',
-  false)
+pnpm run test-all
+
+# pnpm run test-all || (
+#   echo 'Failed tests',
+#   false)
 
 
